services:
  app:
    build: .
    container_name: daily_saas
    restart: always
    # Uncomment if using volumes
    # volumes:
    #   - ./:/app
    ports:
      - "3002:3000"
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: daily_saas_db
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DB

    # Uncomment if using volumes
    # DATABASE_URL="DATABASE_URL"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
