# This "docker-compose.yml" is common base file to :
# "docker-compose.dev.yml" & "docker-compose.prod.yml"
# Listing here things to share commonly between those two files
#--------------------------------------------------------------

services:
  app:
    build: .
    restart: always
    container_name: daily_saas
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: daily_saas_db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - dbdata:/var/lib/postgresql

volumes:
  dbdata:
