# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
#------------------------------------------------------------------------------

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "${DATABASE_URL}"
        NEXT_PUBLIC_MASTER_KEY: "${NEXT_PUBLIC_MASTER_KEY}"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      NEXT_PUBLIC_MASTER_KEY: "${NEXT_PUBLIC_MASTER_KEY}"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start"
    env_file:
      - .env
  db:
    ports: []
